blomqma/next-rest-framework

apps/dev/src/pages/api/nested/route.ts, packages/next-rest-framework/src/utils/open-api.ts, packages/next-rest-framework/tests/paths.test.ts
This fixes a bug where API routes defined
in nested folders were not instrumented by
the OpenAPI generation.
=> Add support for nested folders

apps/dev/src/pages/api/dynamic/[slug]/index.ts, packages/next-rest-framework/src/define-endpoints.ts, packages/next-rest-framework/src/types/method-handlers.ts, packages/next-rest-framework/src/utils/open-api.ts
This fixes the names of dynamic API routes containing route parameters displayed in the Swagger UI. Another change here is that defining the request body and content type is no longer required in the request input object, making it more suitable for any kind of request and GET requests especially.
=> Fix OpenAPI instrumentation for dynamic routes

packages/next-rest-framework/src/define-endpoints.ts, packages/next-rest-framework/tests/index.test.ts
This fixes a bug with middlewares that responded to the API request. Previously the endpoint execution was continued after every middleware and error handler, resulting in an error in the previously mentioned case.
This fixes the issue by checking wheter the request has been ended after proceeding after every middleware and error handler.
=> Fix error with middlewares that respond to API requests

packages/next-rest-framework/src/types/method-handlers.ts, packages/next-rest-framework/src/utils/open-api.ts, packages/next-rest-framework/src/utils/schemas.ts, packages/next-rest-framework/tests/paths.test.ts
Windows uses `\` instead of `/` for path Seperators. This fixes index routes not found on windows files system.
Add path parameters to OpenApi Spec, e.g. `/api/users/{pid}`, the `pid` now shows up in swagger ui
=> Fix path finding for windows environments, and add path parameters to Open API Spec

packages/next-rest-framework/src/utils/open-api.ts
This way the generated output shouldn't differ
between executions of the paths generation.
=> Sort generated OpenAPI paths alphabetically

packages/next-rest-framework/README.md
Fixes a small readme typo, where an app router file path was not named "route.ts"
=> Readme.md fix file path

docs/docs/getting-started.md, packages/next-rest-framework/README.md, packages/next-rest-framework/src/utils/config.ts, packages/next-rest-framework/src/utils/open-api.ts, packages/next-rest-framework/tests/pages-router/paths.test.ts
This fixes an issue where an error occurred on the pages directory not being found when using App Router - this both removes the default config option that sets a default value for the `apiRoutesPath` option, and also gracefully handles the error when either `appDirPath` or `apiRoutesPath` option is enabled but either of those directories are not found.
=> Fix directory not found error when using App Router

apps/example/src/app/layout.tsx
This way it's consistent with the framework's
default theme.
=> Use light theme as default on example app

apps/example/src/pages/api/api-routes/todos.ts, docs/docs/getting-started.md, packages/next-rest-framework/README.md
The readme and docs examples
contained some old implementation
code resulting in TypeScript errors in
the example code.
=> Fix pages router examples

apps/example/src/app/api/routes/todos/route.ts, apps/example/src/pages/api/api-routes/todos.ts, docs/docs/getting-started.md, packages/next-rest-framework/README.md, packages/next-rest-framework/src/define-api-route.ts, packages/next-rest-framework/src/define-route.ts, packages/next-rest-framework/src/utils/schemas.ts, packages/next-rest-framework/tests/app-router/index.test.ts, packages/next-rest-framework/tests/pages-router/index.test.ts
When using App Route and the NextRequest
to validate the request body, we need to clone
the request object to validate the body to allow
further parsing of the request body. Before this
change, trying to parse the request body in the
request handler resulted in an error if the request
body was already parsed by the request body
validation logic.
=> Fix request body validation

apps/example/src/next-rest-framework/client.ts, docs/docs/getting-started.md, packages/next-rest-framework/README.md, packages/next-rest-framework/src/types/config.ts, packages/next-rest-framework/src/utils/open-api.ts
There is a bug when not using the src directory and using the App Router - if the user does not define the `appDirPath` config option having a slash as prefix, the framework won't be able to find the route handlers. This fixes that with a one-line change in the route discovery logic.
The typings for both `appDirPath` and `apiRoutesPath` options are also changed so that the following formats are now supported:
- `src/app`
- `/src/app`
- `./src/app`
=> Fix `appDirPath` handling when not using src directory

packages/next-rest-framework/src/define-api-route.ts, packages/next-rest-framework/src/define-route.ts
This fix changes the content type validation
so that it's done by the framework only when
the user has defined their desired content type
in the inputs. This should address some unexpected errors with various API clients that automatically set the content type header when the user has not set any header validations themselves.
=> Fix content type validation

packages/next-rest-framework/src/docs-handlers.ts, packages/next-rest-framework/src/utils/open-api.ts
This fixes a bug that caused an infinite request
loop when using pages router and the docs endpoint was not ignored by the OpenAPI path generation.
This fix also allows defining multiple different docs endpoints, although that should be a rare case.
The request protocol parsing is also now handled
differently with pages router and cases where the
protocol headers contain multiple protocols should be handled now.
=> Fix infinite request loop with pages router

apps/example/package.json, apps/example/public/openapi.json, docs/docs/api-reference.md, packages/next-rest-framework/README.md, packages/next-rest-framework/package.json, packages/next-rest-framework/src/cli.ts, packages/next-rest-framework/src/docs-handlers.ts, packages/next-rest-framework/src/global.d.ts, packages/next-rest-framework/src/route-handlers.ts, packages/next-rest-framework/src/types/config.ts, packages/next-rest-framework/src/utils/config.ts, packages/next-rest-framework/src/utils/docs.ts, packages/next-rest-framework/src/utils/logging.ts, packages/next-rest-framework/src/utils/open-api.ts, packages/next-rest-framework/tests/app-router/index.test.ts, packages/next-rest-framework/tests/app-router/paths.test.ts, packages/next-rest-framework/tests/pages-router/index.test.ts, packages/next-rest-framework/tests/pages-router/paths.test.ts, packages/next-rest-framework/tests/utils.ts, pnpm-lock.yaml
This improves the CLI performance, makes
it supported in any runtime and adds a new
`next-rest-framework validate` command, that
checks that the generated `openapi.json` file
is up to date. The CLI commands no longer
spin up the Next.js dev server, but instead
optionally run `next build` to generate the
routes and generates the OpenAPI paths from
those generated routes.
=> Make CLI great again

packages/next-rest-framework/src/docs-handlers.ts, packages/next-rest-framework/src/utils/open-api.ts
This fixes request handling when using
a proxy or HTTPS connections locally.
The request protocol/host parsing is fixed
and validated now similarly on both routers.
Additionally, the TLS certificate validation
is disabled when developing locally.
=> Fix request handling with proxies

packages/next-rest-framework/src/index.ts, packages/next-rest-framework/src/types/index.ts, packages/next-rest-framework/src/types/route-handlers.ts, packages/next-rest-framework/src/types/typed-next-response.ts
Previously, the problem with App Router was that
truly strongly-typed responses were not possible due to the `NextResponse` class not supporting a generic typing of the status codes. This change adds a patched `TypedNextResponse` class that adds support for
type-checking the response status codes based on
the output schema.
In order to achieve this, the user must import the `TypedNextResponse` class from Next REST Framework, but the good thing is that this is fully optional and using the plain `NextResponse` is still supported if the user prefers not to have strongly typed status code checks.
=> Add support for strongly-typed NextResponse

packages/next-rest-framework/package.json
The preinstall script that injects the node env
shebang to the dist CLI script is no longer needed as that gets automatically included in the build
output and having that UNIX-specific syntax in
the preinstall script breaks the installation on
Windows.
=> Remove shebang injection from preinstall

packages/next-rest-framework/src/utils/open-api.ts, packages/next-rest-framework/tests/app-router/paths.test.ts, packages/next-rest-framework/tests/pages-router/paths.test.ts, packages/next-rest-framework/tests/utils.ts
=> Fix issue with OpenAPI spec generator failing to generate valid paths when more than one path parameter exists 

packages/next-rest-framework/src/docs-handlers.ts, packages/next-rest-framework/src/utils/docs.ts, packages/next-rest-framework/tests/app-router/index.test.ts, packages/next-rest-framework/tests/pages-router/index.test.ts
For HTTP production environments that are not configured to use the `x-forwarded-proto` header, the API docs will default the fetch the `openapi.json` over plain HTTP, leading to mixed content errors. This change uses content-relative URL to fetch the `openapi.json`, which defaults to the currently used protocol.
=> Use content-relative URL for fetching `openapi.json` in docs

apps/example/package.json, packages/next-rest-framework/src/cli.ts
This adds a debug option for the CLI commands
to get the build logs from the next build step.
=> Add CLI debug logging option

packages/next-rest-framework/src/utils/open-api.ts
This fix imports all named prettier exports
as a single module according to the prettier
API documentation: https://prettier.io/docs/en/api.html
This is a potential fix for a module resolution issue that causes a crash in some environments where
the default import causes "module" not being found.
=> Update prettier import syntax

apps/example/public/openapi.json, apps/example/src/app/api/routes/rpc/route.ts, apps/example/src/app/api/routes/todos/route.ts, package.json, packages/next-rest-framework/src/app-router/route-handler.ts, packages/next-rest-framework/src/app-router/route-operation.ts, packages/next-rest-framework/src/app-router/rpc-route-handler.ts, packages/next-rest-framework/src/pages-router/api-route-handler.ts, packages/next-rest-framework/src/pages-router/api-route-operation.ts, packages/next-rest-framework/src/pages-router/rpc-api-route-handler.ts, packages/next-rest-framework/src/shared/open-api.ts, packages/next-rest-framework/src/shared/rpc-operation.ts, packages/next-rest-framework/src/types.ts, packages/next-rest-framework/tests/app-router/paths.test.ts, packages/next-rest-framework/tests/app-router/rpc.test.ts, packages/next-rest-framework/tests/pages-router/paths.test.ts, packages/next-rest-framework/tests/pages-router/rpc.test.ts, packages/next-rest-framework/tests/utils.ts, pnpm-lock.yaml
This change improves the OpenAPI spec
generation by introducing auto-generated
schema objects that can be used across
different operations.
Additionally, swagger-cli is introduced as
part of the CI pipeline to validate that the
generated OpenAPI document is valid.
=> Improve OpenAPI generation

packages/next-rest-framework/src/cli.ts
I had a problem with the way the data was merged and I fixed it.
=> fix data structure to merge

packages/next-rest-framework/src/shared/docs.ts, packages/next-rest-framework/src/types.ts
This fixes the typings for the optional
OpenAPI documentation parameters
that can be used to extend the generated
document. Not all properties are optional.
=> Fix OpenAPI typings

docs/docs/api-reference.md, packages/next-rest-framework/README.md, packages/next-rest-framework/src/app-router/route-operation.ts, packages/next-rest-framework/src/app-router/route.ts, packages/next-rest-framework/src/app-router/rpc-route.ts, packages/next-rest-framework/src/pages-router/api-route-operation.ts, packages/next-rest-framework/src/pages-router/api-route.ts, packages/next-rest-framework/src/pages-router/rpc-api-route.ts, packages/next-rest-framework/src/shared/rpc-operation.ts, packages/next-rest-framework/src/types.ts, packages/next-rest-framework/tests/app-router/index.test.ts, packages/next-rest-framework/tests/app-router/rpc.test.ts, packages/next-rest-framework/tests/pages-router/index.test.ts, packages/next-rest-framework/tests/pages-router/rpc.test.ts
This change allows chaining up to three
middleware functions together and sharing
data between the middlewares.
=> Add support for multiple middlewares

apps/example/.eslintrc.json, packages/next-rest-framework/src/app-router/rpc-route.ts
The request body of an RPC request
was incorrectly passed as a ReadableStream
object for the RPC handlers and middlewares
while it should be passed as JSON.
=> Fix RPC request body parsing 

packages/next-rest-framework/src/app-router/route.ts
This fixes the handling of custom responses
from the middleware handlers. Comparing the
instance to a `NextResponse` object was not
working while using the `Response` object that
the NextResponse object is also inherited from,
seems to fix the issue so that custom responses
from middlewares work.
=> Fix middleware response handling

packages/next-rest-framework/src/app-router/route-operation.ts, packages/next-rest-framework/src/app-router/rpc-route.ts, packages/next-rest-framework/src/pages-router/api-route-operation.ts, packages/next-rest-framework/tests/app-router/route.test.ts, packages/next-rest-framework/tests/app-router/rpc-route.test.ts, packages/next-rest-framework/tests/pages-router/api-route.test.ts, packages/next-rest-framework/tests/pages-router/rpc-api-route.test.ts
This fixes a bug where an RPC route
returned an error when a middleware
was used and the operation has no input.
This also fixes the typings for `route`/`apiRoute`
middlewares where asynchronous middleware
function responses were not typed correctly.
=> Fix middleware data passing

apps/example/public/openapi.json, apps/example/src/app/api/v2/route-with-query-params/route.ts, apps/example/src/pages/api/v1/route-with-query-params/index.ts, docs/docs/getting-started.md, packages/next-rest-framework/README.md, packages/next-rest-framework/package.json, packages/next-rest-framework/src/app-router/route.ts, packages/next-rest-framework/src/shared/paths.ts, packages/next-rest-framework/tests/app-router/route.test.ts, packages/next-rest-framework/tests/pages-router/api-route.test.ts, packages/next-rest-framework/tests/utils.ts, pnpm-lock.yaml
The OpenAPI spec generation for query
parameters ended up adding unnecessary
union types for the generated schema which
is fixed here.
The query parameter parsing is now done with
the `qs` library instead of the previous manual
parsing and some test coverage is added to handle
both valid and invalid query parameter calls.
=> Fix query parameter OpenAPI generation

packages/next-rest-framework/src/cli/utils.ts
This option resulted in the CLI not working for some users due to the required dependencies not being resolved.
=> Remove ESBuild extenal packages option from CLI bundling

docs/docs/api-reference.md, packages/next-rest-framework/README.md, packages/next-rest-framework/src/shared/config.ts, packages/next-rest-framework/src/types.ts
This is dead code and not used for anything
anymore. This also fixes some misinformation
in the docs.
=> Remove `suppressInfo` config option

packages/next-rest-framework/package.json, packages/next-rest-framework/src/cli/utils.ts, pnpm-lock.yaml
The ESBuild process for the CLI commands
fails when run with npm/npx due to the dependencies being resolved differently than with pnpm, resulting in the dependencies at node_modules folder being resolved by ESBuild when running the CLI commands with npm/npx.
To fix this, the `tiny-glob` package is replaced with an alternative `fast-glob` that allows us to explicitly exclude all node_modules files from the globbing output, fixing the issue.
=> Fix CLI bundling glob for npm/npx

packages/next-rest-framework/src/cli/utils.ts
hi,
noticed an issue with the pages router when using the `/src/pages/api` path due to this hardcoded path within the `findConfig` function. 
The examples would also not run for me, after the change all was good 👍 
did some debugging and traced it back to this hardcoded path:
=> fix pages router not generating due to hardcoded path

apps/example/package.json, apps/example/public/openapi.json, apps/example/src/app/api/v2/route-with-external-dep/route.ts, apps/example/src/pages/api/v1/route-with-external-dep/index.ts, apps/example/src/scripts/custom-generate-openapi.ts, apps/example/src/scripts/custom-validate-openapi.ts, docs/docs/api-reference.md, docs/docs/getting-started.md, docs/docs/intro.md, packages/next-rest-framework/README.md, packages/next-rest-framework/package.json, packages/next-rest-framework/src/cli/constants.ts, packages/next-rest-framework/src/cli/generate.ts, packages/next-rest-framework/src/cli/index.ts, packages/next-rest-framework/src/cli/utils.ts, packages/next-rest-framework/src/cli/validate.ts, packages/next-rest-framework/tsup.config.ts, pnpm-lock.yaml
This fix aims to address various ESBuild issues of users by removing the ESBuild step from the CLI
commands and parsing parsing the OpenAPI spec
directly from TS/JS files without any build step by using tsx.
The `generate` and `validate` functions are now
also exposed as entry points for the ESBuild output, allowing those functions to be used for custom CLIs.
The second commit also includes verifying that the CLI commands work with third-party dependencies, raised in this PR: https://github.com/blomqma/next-rest-framework/pull/160
=> Remove CLI ESBuild step

apps/example/src/app/page.tsx, packages/next-rest-framework/src/app-router/route-operation.ts, packages/next-rest-framework/src/index.ts, packages/next-rest-framework/src/pages-router/api-route-operation.ts, packages/next-rest-framework/src/types.ts, packages/next-rest-framework/tests/app-router/route.test.ts
This fixes the TS error when using an async
middleware by fixing the return types of the
middleware function. This also exports the typings
of `TypedNextRerquest`, `TypedNextApiRequest` and
`TypedNextApiResponse` so that they can be used for
custom abstractions.
=> Fix async middleware typings

docs/docs/getting-started.md, packages/next-rest-framework/README.md, packages/next-rest-framework/src/app-router/docs-route.ts
Currently in the app router docs route we read the request headers directly from the original request object. This is problematic because it leads to a dynamic server usage error unless the docs endpoint is explicitly set to `force-dynamic` caching strategy. By reading the headers from a cloned request object the docs endpoint can be used with the default caching strategy, fixing this issue.
=> Fix dynamic server usage in app router docs route

packages/next-rest-framework/src/pages-router/api-route-operation.ts
Body for the page routes is always `never` unless you're using a form.
I believe original intention was only to be `never` when the method is GET.
=> Patch page body type

apps/example/public/openapi.json, packages/next-rest-framework/src/app-router/route.ts, packages/next-rest-framework/src/constants.ts, packages/next-rest-framework/src/pages-router/api-route.ts, packages/next-rest-framework/src/shared/paths.ts, packages/next-rest-framework/tests/app-router/route.test.ts, packages/next-rest-framework/tests/pages-router/api-route.test.ts, packages/next-rest-framework/tests/utils.ts
This improves the auto-generated response
documentation by dynamically including different
response schemas for invalid request bodies, invalid query parameters etc. to the auto-generated OpenAPI schema based on the defined endpoints.
=> Fix error response schemas

packages/next-rest-framework/src/cli/utils.ts, packages/next-rest-framework/src/shared/logging.ts
This adds error messages whenever generating OpenAPI paths fail for routes, helping debugging any issues in those.
=> Improve error handling for generating OpenAPI paths

packages/next-rest-framework/src/cli/utils.ts
This adds a fallback for importing the modules
as CJS modules if importing the ESM default
export leads to undefined.
=> Add support for CJS imports in generate

apps/example/src/actions.ts, apps/example/src/app/layout.tsx, package.json, packages/next-rest-framework/src/app-router/docs-route.ts, packages/next-rest-framework/src/app-router/route.ts, packages/next-rest-framework/src/app-router/rpc-route.ts, pnpm-lock.yaml
=> feat: Support next 15
